project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    linestretch: 2
    comments:
      hypothesis: true
  docx:
    linestretch: 2
  jats: default
  #agu-pdf: default
  arxiv-pdf: default



